# Generated by Django 5.2.5 on 2026-04-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_platformsettings_app_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa (10%)'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Líquido (A Pagar)'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto (Total)'),
        ),
    ]
